language: php

php:
  - 7.1

go:
  - 1.8

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source
  - go get "github.com/spiral/goridge"

script:
  - go run tests/server.go &
  - go run tests/socket4bytes.go &
  - go run tests/socket10echo.go &
  - vendor/bin/phpunit --coverage-clover=clover.xml tests/

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose --config .coveralls.yml